name: client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  drift: ^2.5.0
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_svg: null
  fluttermoji: ^1.0.1
  google_sign_in: ^6.0.1
  http: ^0.13.5
  intl: null
  multiavatar: ^0.1.5
  path: ^1.8.2
  path_provider: ^2.0.0
  provider: ^6.0.5
  shared_preferences: 
  sqlite3_flutter_libs: ^0.5.0
  stacked: ^3.1.0+2
  web_socket_channel: ^2.3.0

dev_dependencies:
  mockito: ^5.4.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  drift_dev: ^2.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  socket_io_client: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
