name: client
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.2
  dartz: ^0.10.1
  drift: ^2.5.0
  equatable: ^2.0.5
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: null
  fluttermoji: ^1.0.1
  google_sign_in: ^6.0.1
  http: ^0.13.5
  intl: null
  meta: ^1.9.1
  multiavatar: ^0.1.5
  path: ^1.8.2
  path_provider: ^2.0.0
  provider: ^6.0.5
  shared_preferences: null
  web_socket_channel: ^2.3.0
  sqflite:
  flutter_simple_dependency_injection:
  font_awesome_flutter: ^9.0.0
  flutter_webrtc:
  sdp_transform:
  flutter_callkit_incoming: ^2.0.0+1
  uuid:
  get: ^4.6.5
  get_storage:
  custom_search_bar: ^0.0.3
  awesome_notifications: ^0.7.4+1
  flutter_ringtone_player: ^3.2.0
  connectivity_plus: ^4.0.2
  flutter_blurhash: ^0.7.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  drift_dev: ^2.5.1
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
